version: "3.9"
services:
  web:
    build:
      context: .
      args: 
        PYTHON_VERSION: ${PYTHON_VERSION}
    container_name: "intertwino_api"
    ports:
      - "${API_PORT}:5000"
    restart: always
    environment:
      FLASK_DEBUG: 1
    env_file:
      - ./.env  
    volumes:
      - .:/code  
      
  mongo:
    image: "mongo:${MONGO_VERSION}"
    container_name: "intertwino_mongo"
    ports:
      - "${MONGO_PORT}:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
     volumes:
      - ./mongo-data:/data/db
    
  jupyter:
    image: "jupyter/datascience-notebook:${JUPYTER_VERSION}"
    container_name: intertwino_jupyter
    env_file:
      - ./.env
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    ports:
      - "${JUPYTER_PORT}:8888"
    restart: always  
    volumes:
      - ./work:/home/jovyan/work
      
